version: 11.7.{build}
image: Visual Studio 2022
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: nuget restore
build:
  project: CSCuda.sln
  publish_nuget: true
  verbosity: normal
after_build:
- ps: .\pack.ps1
test: off
artifacts:
- path: CSCuda\bin\$(configuration)\net6.0-windows\CSCuda.dll
  name: CSCuda.dll
- path: CSCuda.NPP\bin\$(configuration)\net6.0-windows\CSCuda.NPP.dll
  name: CSCuda.NPP.dll
- path: CSCuda.CUBLAS\bin\$(configuration)\net6.0-windows\CSCuda.CUBLAS.dll
  name: CSCuda.CUBLAS.dll
- path: CSCuda*.nupkg
- path: README.md
  name: README.md
deploy:
- provider: NuGet
  api_key:
    secure: 655MRVhUca4e6pq3iUY26xdAqRYK/quSsTauo9kHqVcQJbJ52uzNCj2YEFaw5uqT
  skip_symbols: false
  artifact: /.*\.nupkg/